### ISSUE TITLE
 Audit.NET.SQLServer fails to insert an audit event if there is CustomColumn with value of null. 

### ISSUE THREAD

**Issue by mmarquezs** [thepirat000/Audit.NET#357]
**Describe the bug**
When setting a CustomColumn value as null the audit fails to save throwing an error complaining about a missing parameter.
The audit table custom column is nullable in the database.

The closest bug I found was this one #303 but they simply removed the column as I just did for now and in their case is using the PostgreSQL extension instead of the SQL server one that I'm using.

**To Reproduce**
1. Use the Audit.NET.SQLServer Extension
2. Create the Audit Table in the SQL Server database with a nullable Column that will be used as CustomColumn. We will call it "ExampleNullableColumn"
3. Define the nullable column as a CustomColumn with a null as value. (This is just for reproducing it, in my case it's based on a custom field filled during the audit scope creation that sometimes is null if the field is no relevant for that audit event)
 Ex: .CustomColumn("ExampleNullableColumn", ev => null); 
4. On saving the audit it will throw and error complaining about a parameter @c0 (or @c**n** depending of the **n** number of existing customcolumns) that was not supplied when attempting to insert into the audit table. (In my case it was c1 because it's the second CustomColumn I have, the other one doesn't give me any issues). 

**Expected behavior**
The nullable column of the audit table is filled if the custom column value is not null and if it's null it allows it to save it anyway since the destination it's a nullable column.

**Libraries (specify the Audit.NET extensions being used including version):**
For example:
 - Audit.NET: v16.1.5
 - Audit.EntityFramework.Core: v16.1.5
 - Audit.EntityFramework.Identity.Core: v16.1.5
 - Audit.NET.SQLServer: v16.1.5

**Target .NET framework:**
For example:
 - .NET Core 3.1

**Comment by thepirat000** [comment]
Can you try by casting the null to the appropriate type? Assuming it's a `Nullable<int>` please try with

`.CustomColumn("ExampleNullableColumn", ev => (int?)null);`

**Comment by thepirat000** [comment]
Closing this for inactivity. If you're still having this issue please comment

**Comment by mmarquezs** [comment]
Oh Sorry  about that I thought I did send a reply. 
Here it goes again then: 
I did test what you suggested but I got the same issue it was still complaining about a missing parameter (in this case I just left the nullable custom column).
My audit core setup:
```
Audit.Core.Configuration.Setup()
  .UseSqlServer(config => config
    .ConnectionString(this.GetConnectionString())
    .TableName("AuditLogEvents")
    .IdColumnName("Id")
    .JsonColumnName("JsonData")
    .CustomColumn("UserId", ev => (int?)null)); 
```
The error once an event happens and triggers the audit save:
`The parameterized query '(@json nvarchar(881),@c0 nvarchar(4000))INSERT INTO [AuditLogEvent' expects the parameter '@c0', which was not supplied.`

**Comment by thepirat000** [comment]
I see what the problem is. You can avoid the problem by using `DBNull.Value`

`.CustomColumn("UserId", ev => DBNull.Value));`

Anyway I will fix the problem on the library to change the NULLs to DBNull for the custom column values

**Comment by thepirat000** [comment]
This was fixed on version 16.4.4, please upgrade your references and re-test.

**Comment by dombavetta** [comment]
@thepirat000 Just a heads up, I ran into this issue using version 19.0.5 of both `Audit.Net` and `Audit.NET.PostgreSql`. Changing the return use `DBNull.value` did get me through it but I just wanted to note that this is still not supporting `null` as a value.

**Comment by thepirat000** [comment]
This was fixed for [PostgreSql](https://github.com/thepirat000/Audit.NET/blob/master/src/Audit.NET.PostgreSql/README.md) extension on version 19.0.6, please upgrade your references and re-test
